In [3]:
import pandas as pd
data = pd.read_csv("spam_ham_dataset 2.csv")
data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
data[data["Category"]=="ham"]

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
6         ham  Even my brother is not like to speak with me. ...
...       ...                                                ...
5565      ham                                       Huh y lei...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[4825 rows x 2 columns]

In [5]:
data.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [6]:
data['Category']=data['Category'].map({"ham":1, "spam":2})
data

Category                                            Message
0            1  Go until jurong point, crazy.. Available only ...
1            1                      Ok lar... Joking wif u oni...
2            2  Free entry in 2 a wkly comp to win FA Cup fina...
3            1  U dun say so early hor... U c already then say...
4            1  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567         2  This is the 2nd time we have tried 2 contact u...
5568         1               Will ü b going to esplanade fr home?
5569         1  Pity, * was in mood for that. So...any other s...
5570         1  The guy did some bitching but I acted like i'd...
5571         1                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.Message, data.Category)

In [8]:
 from sklearn.feature_extraction.text import CountVectorizer
 vectorizer = CountVectorizer()
 X_vec_train = vectorizer.fit_transform(X_train.values)

In [9]:
 X_vec_train.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
X_vec_test = vectorizer.transform(X_test)

In [11]:
X_vec_test.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit( X_vec_train, y_train)


MultinomialNB()

In [13]:
clf.score(X_vec_test,y_test)


0.9784637473079684

In [14]:
email = ['20-70% off watches and accessories Khadijah',
         'Will Smith newest movie is finally here!!']
email_c = vectorizer.transform(email)
clf.predict(email_c)

array([1, 1])

In [18]:
import pickle as pk
pk.dump(clf, open("clf.pkl", "wb"))

In [ ]:
#check if the server work OK 

In [19]:
import requests
import json

In [29]:
example = vectorizer.transform(['Will Smith newest movie is finally here!!'])
example

<1x7438 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [30]:
# local url
url = 'http://127.0.0.1:5000/' # URL in the output


example = vectorizer.transform("20-70% off watches and accessories Khadijah")
# test data


example
data = {'Message': example}

data = json.dumps(example)
data

ValueError: Iterable over raw text documents expected, string object received.